[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "quickdict"
version = "1.0"
description = "Quick Python dictionary operations."
readme = "README.md"
requires-python = ">=3.12"
license = "MIT"
license-files = ["LICEN[CS]E*"]
authors = [
  {name="Sebastian Gössl", email="goessl@student.tugraz.at"}
]

[project.urls]
Homepage = "https://github.com/goessl/quickdict"
Documentation = "https://goessl.github.io/quickdict"
Repository = "https://github.com/goessl/quickdict.git"

[project.optional-dependencies]
test = ["pytest"]

[[tool.setuptools.ext-modules]]
name = "quickdict.mapping._mapping"
sources = ["quickdict/mapping/_mappingmodule.c"]
py-limited-api = true

[[tool.setuptools.ext-modules]]
name = "quickdict.filtering._filtering"
sources = ["quickdict/filtering/_filteringmodule.c"]
py-limited-api = true
