from typing import Callable, TypeVar
from collections.abc import Mapping, MutableMapping



__all__ = ('qd_filter',    'pyqd_filter',
           'qd_kfilter',   'pyqd_kfilter',
           'qd_kvfilter',  'pyqd_kvfilter',
           'qd_ifilter',   'pyqd_ifilter',
           'qd_ikfilter',  'pyqd_ikfilter',
           'qd_ikvfilter', 'pyqd_ikvfilter')



K, V = TypeVar('K'), TypeVar('V')



def qd_filter(p:None|Callable[[V],bool], m:Mapping[K,V]) -> dict[K,V]: ...
def pyqd_filter(p:None|Callable[[V],bool], m:Mapping[K,V]) -> dict[K,V]: ...

def qd_kfilter(p:Callable[[K],bool], m:Mapping[K,V]) -> dict[K,V]: ...
def pyqd_kfilter(p:Callable[[K],bool], m:Mapping[K,V]) -> dict[K,V]: ...

def qd_kvfilter(p:Callable[[K,V],bool], m:Mapping[K,V]) -> dict[K,V]: ...
def pyqd_kvfilter(p:Callable[[K,V],bool], m:Mapping[K,V]) -> dict[K,V]: ...


def qd_ifilter(p:None|Callable[[V],bool], m:MutableMapping[K,V]) -> MutableMapping[K,V]: ...
def pyqd_ifilter(p:None|Callable[[V],bool], m:MutableMapping[K,V]) -> MutableMapping[K,V]: ...

def qd_ikfilter(p:Callable[[K],bool], m:MutableMapping[K,V]) -> MutableMapping[K,V]: ...
def pyqd_ikfilter(p:Callable[[K],bool], m:MutableMapping[K,V]) -> MutableMapping[K,V]: ...

def qd_ikvfilter(p:Callable[[K,V],bool], m:MutableMapping[K,V]) -> MutableMapping[K,V]: ...
def pyqd_ikvfilter(p:Callable[[K,V],bool], m:MutableMapping[K,V]) -> MutableMapping[K,V]: ...
